#!/bin/bash
# gitst
# Copyright (c) 2013 Jeffrey S. Pitblado

if [ "$#" = "0" ]
then
	git status --short . | awk "{print \$NF}" | sort
else
	args=()
	for arg; do args+=("$arg"); done
	git status --short . | grep "${args[@]}" | awk "{print \$NF}" | sort
fi

exit
