#!/bin/sh
# gitst
# Copyright (c) 2013 Jeffrey S. Pitblado

if [ "$#" = "0" ]
then
	git status --short . | awk "{print \$NF}" | sort
else
	git status --short . | grep "${@}" | awk "{print \$NF}" | sort
fi

exit
