#!/bin/bash
# svn-list-ignored

self=`basename $0`

Usage () {
	cat 1>&2 << EOF
Usage: $self <dirlist>

$self loops over the directories within <dirlist> and calls

	# svn status --no-ignore <dir> | grep "^I"

This script is useful for finding ignored files and folders that exist
in your working copy.

Example:

	# $self .

EOF
	exit 1
}

if [ ${#} -eq 0 ]
then
	Usage
fi

for item in ${*}
do
	svn status --no-ignore "${item}" | grep "^I"
done

exit
