#!/bin/bash
# svnst
# Copyright (c) 2005 Jeffrey S. Pitblado

if [ "$#" = "0" ]
then
	svn st | awk "{print \$NF}" | sort
else
	args=()
	for arg; do args+=("$arg"); done
	svn st | grep "${args[@]}" | awk "{print \$NF}" | sort
fi

exit
