# bash/bashrc

if [ -z "$DOTFILES" ]
then
	export DOTFILES=$HOME/.dotfiles
fi

. $DOTFILES/sh/debug_msg.sh

for file in `find -L "$DOTFILES" -name "*.shrc"`
do
	debug_msg "sourcing $file"
	. $file
done

for file in `find -L "$DOTFILES" -name "*.bashrc"`
do
	debug_msg "sourcing $file"
	. $file
done

unset pathmunge
unset debug_msg

# end: bash/bashrc
