# bash/bashrc

if [ -z "$DOTFILES" ]
then
	export DOTFILES=$HOME/.dotfiles
fi

. $DOTFILES/sh/debug_msg.sh

for file in `find -L "$DOTFILES" -name "*.shrc"`
do
	debug_msg "sourcing $file"
	. $file
done

# reverse sort order to ensure prompt.bashrc is sourced after
# svn-prompt.bashrc
for file in `find -L "$DOTFILES" -name "*.bashrc" | sort -r`
do
	debug_msg "sourcing $file"
	. $file
done

unset pathmunge
unset debug_msg

# end: bash/bashrc
